<?php

namespace ProfBundle\Repository;

/**
 * AbsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbsRepository extends \Doctrine\ORM\EntityRepository
{
}
