<?php

namespace ProfBundle\Repository;

/**
 * ProfsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfsRepository extends \Doctrine\ORM\EntityRepository
{
}
